# Pandas

## Introduction to Pandas

This section is basically for importing pandas, reading files and knowing how to select using the iloc method and the shortcuts.

Important functions are **df.info()** and **df[column].value_counts()** and **pd.read_csv** or **pd.read_excel**

In [1]:
# importing pandas
import pandas as pd

In [4]:
#Read a file
test = pd.read_excel('gasolina.xlsx')

In [9]:
#Describing the set
print(test.shape)

(4617, 18)

In [10]:
print(test.head())

  Marca Submarca                                        Versión  Modelo  \
0  FORD   FUSION         HIBRIDO 4PTS 2.0L 4CIL 188HP AUT (CVT)    2015
1  FORD   FUSION        HIBRIDO 4PTS 2.0L 4CIL 188HP AUT (eCVT)    2016
2  FORD   FUSION  HIBRIDO 4X2 4PTAS 2.0L 4CIL 141(+47e)HP E-CVT    2017
3  FORD   FUSION         HIBRIDO 4PTAS 2.0L 4CIL 188HP AUT eCVT    2018
4  FORD   FUSION                HYBRID 4PTS 2.5L 4CIL 156HP CVT    2011

  Trans.     Comb.  Cilindros  Potencia (HP)  Tamaño (L)        Categoría  \
0    CVT  Gasolina          4            188         2.0  AUTOS COMPACTOS
1    CVT  Gasolina          4            188         2.0  AUTOS COMPACTOS
2    CVT  Gasolina          4            188         2.0  AUTOS COMPACTOS
3    AUT  Gasolina          4            188         2.0  AUTOS COMPACTOS
4    CVT  Gasolina          4            156         2.5  AUTOS COMPACTOS

   R. Ciudad (km/l)  R. Carr. (km/l)  R. Comb. (km/l)  R. Ajust. (km/l)  \
0             27.44            28.57            28.93             21.70
1             27.44            28.57            28.93             21.70
2             25.62            24.77            25.23             18.92
3             25.62            24.77            25.23             18.92
4             24.00            21.90            23.01             17.26

   CO2(g/km)  NOx (g/1000km)  Calificación Gas Ef. Inv.  \
0        107               5                         10
1        107               0                         10
2        123               2                         10
3        123               2                         10
4        135               5                          9

  Calificación Contam. Aire
0                         9
1                         9
2                         9
3                         9
4                         9

In [11]:
print(test.dtypes)

Marca                         object
Submarca                      object
Versión                       object
Modelo                         int64
Trans.                        object
Comb.                         object
Cilindros                      int64
Potencia (HP)                  int64
Tamaño (L)                   float64
Categoría                     object
R. Ciudad (km/l)             float64
R. Carr. (km/l)              float64
R. Comb. (km/l)              float64
R. Ajust. (km/l)             float64
CO2(g/km)                      int64
NOx (g/1000km)                 int64
Calificación Gas Ef. Inv.      int64
Calificación Contam. Aire     object
dtype: object

In [12]:
print(test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4617 entries, 0 to 4616
Data columns (total 18 columns):
Marca                        4617 non-null object
Submarca                     4617 non-null object
Versión                      4617 non-null object
Modelo                       4617 non-null int64
Trans.                       4601 non-null object
Comb.                        4617 non-null object
Cilindros                    4617 non-null int64
Potencia (HP)                4617 non-null int64
Tamaño (L)                   4617 non-null float64
Categoría                    4617 non-null object
R. Ciudad (km/l)             4617 non-null float64
R. Carr. (km/l)              4617 non-null float64
R. Comb. (km/l)              4617 non-null float64
R. Ajust. (km/l)             4617 non-null float64
CO2(g/km)                    4617 non-null int64
NOx (g/1000km)               4617 non-null int64
Calificación Gas Ef. Inv.    4617 non-null int64
Calificación Contam. Aire    4617 non-null object
dtypes: float64(5), int64(6), object(7)
memory usage: 649.3+ KB
None

In [29]:
# Selection using labels
print(test.loc[14])
print('-----------')
print(test.loc[14,"Marca"])
print('-----------')
print(test.head()["Marca"])
print('-----------')
print(test.head()[["Marca", "Cilindros"]])
print('-----------')
print(test.loc[50 : 53])

Marca                                                          MAZDA
Submarca                                                      MAZDA2
Versión                      i TOURING 5PTAS 1.5L 4CIL 106HP AUT R15
Modelo                                                          2016
Trans.                                                           AUT
Comb.                                                       Gasolina
Cilindros                                                          4
Potencia (HP)                                                    106
Tamaño (L)                                                       1.5
Categoría                                            AUTOS COMPACTOS
R. Ciudad (km/l)                                                17.3
R. Carr. (km/l)                                                   24
R. Comb. (km/l)                                                 21.1
R. Ajust. (km/l)                                               15.83
CO2(g/km)                                                        147
NOx (g/1000km)                                                     9
Calificación Gas Ef. Inv.                                          9
Calificación Contam. Aire                                          9
Name: 14, dtype: object
-----------
MAZDA
-----------
0    FORD
1    FORD
2    FORD
3    FORD
4    FORD
Name: Marca, dtype: object
-----------
  Marca  Cilindros
0  FORD          4
1  FORD          4
2  FORD          4
3  FORD          4
4  FORD          4
-----------
     Marca Submarca                         Versión  Modelo Trans.     Comb.  \
50    SEAT   TOLEDO        4PTAS 1.6L 4CIL110HP MAN    2016    MAN  Gasolina
51    SEAT   TOLEDO        4PTAS 1.6L 4CIL110HP MAN    2017    MAN  Gasolina
52   MAZDA   MAZDA3  SEDAN 4PTS 2.0L 4CIL 155HP AUT    2016    AUT  Gasolina
53  NISSAN   SENTRA       4PTAS 1.8L 4CIL 129HP MAN    2016    CVT  Gasolina

    Cilindros  Potencia (HP)  Tamaño (L)        Categoría  R. Ciudad (km/l)  \
50          4            110         1.6  AUTOS COMPACTOS              15.7
51          4            110         1.6  AUTOS COMPACTOS              15.7
52          4            155         2.0  AUTOS COMPACTOS              15.7
53          4            129         1.8  AUTOS COMPACTOS              15.7

    R. Carr. (km/l)  R. Comb. (km/l)  R. Ajust. (km/l)  CO2(g/km)  \
50            25.80            19.06             14.29        163
51            25.80            19.06             14.29        163
52            23.70            19.86             14.89        157
53            23.25            18.39             13.79        169

    NOx (g/1000km)  Calificación Gas Ef. Inv. Calificación Contam. Aire
50               7                          8                         9
51               7                          8                         9
52               5                          8                         9
53              19                          8                         7

In [41]:
# Getting frequency tables of a column (attribute)
brands_frequency = test["Marca"].value_counts()
print(brands_frequency)
# Shortcuts for selection on series (i.e. only one column on the data set) work different
print(brands_frequency.loc["AUDI"])

AUDI           424
PORSCHE        420
MERCEDES       374
VW             319
CHEVROLET      296
BMW            267
FORD           257
NISSAN         204
HONDA          203
MAZDA          160
DODGE          131
MINI           127
SEAT           105
TOYOTA          92
PEUGEOT         91
JEEP            83
VOLVO           81
SUBARU          77
CADILLAC        77
SUZUKI          75
FIAT            71
ACURA           67
HYUNDAI         55
INFINITI        55
MITSUBISHI      52
LINCOLN         51
BENTLEY         50
RENAULT         47
KIA             45
LAND ROVER      40
JAGUAR          33
CHRYSLER        32
SMART           31
BUICK           30
GMC             29
LAMBORGHINI     17
ALFA ROMEO      17
ROLLSROYCE      15
SAAB             8
GML              4
MERCURY          2
LEXUS            2
MAYBACH          1
Name: Marca, dtype: int64
424

## Exploring Data Intro

This part is basically about descriptive statistics and boolean indexing

- operations are vectorized
- descirptive statistics summary
- **df.describe** and s.describe
- boolean indexing

In [47]:
#operations are vectorized on pandas (just as they are on numpy)
cilindros_series = test["Cilindros"]
print(cilindros_series.head() +5)
print(cilindros_series.head()  * 5)
print(cilindros_series.head()  / 2)

0    9
1    9
2    9
3    9
4    9
Name: Cilindros, dtype: int64
0    20
1    20
2    20
3    20
4    20
Name: Cilindros, dtype: int64
0    2.0
1    2.0
2    2.0
3    2.0
4    2.0
Name: Cilindros, dtype: float64

In [53]:
#pandas have the normal descriptive tools
print(cilindros_series.min())
print(cilindros_series.max())
print(cilindros_series.mean())
print(cilindros_series.median())
print(cilindros_series.mode())
print(cilindros_series.sum())

3
12
5.329218106995885
4.0
0    4
dtype: int64
24605

In [54]:
print(cilindros_series.describe())

count    4617.000000
mean        5.329218
std         1.800226
min         3.000000
25%         4.000000
50%         4.000000
75%         6.000000
max        12.000000
Name: Cilindros, dtype: float64

In [59]:
#Getting usefull descriptive measures only for some columns (or even rows) of the data set
print(test[["Modelo", "Cilindros"]].median(0))
print(test[["Modelo", "Cilindros"]].median(1).head())

Modelo       2014.0
Cilindros       4.0
dtype: float64
0    1009.5
1    1010.0
2    1010.5
3    1011.0
4    1007.5
dtype: float64

In [81]:
# Boolean Indexing

only_toyotas_boolean = test["Marca"] == "TOYOTA"
only_toyotas_boolean.value_counts()
print(test.loc[only_toyotas_boolean, "Marca"].head())

#boolean indexing shortcut
print(test[test["Submarca"] == "CAMRY"])

#Gettin only an specific column after using boolean indexing
print(test.loc[only_toyotas_boolean, "Marca"].head())

print(test.loc[only_toyotas_boolean, "R. Ciudad (km/l)"].mode())

501    TOYOTA
502    TOYOTA
503    TOYOTA
504    TOYOTA
505    TOYOTA
Name: Marca, dtype: object
       Marca Submarca                   Versión  Modelo Trans.     Comb.  \
917   TOYOTA    CAMRY  4PTS 2.5L 4CIL 178HP AUT    2012    AUT  Gasolina
918   TOYOTA    CAMRY  4PTS 2.5L 4CIL 178HP AUT    2013    AUT  Gasolina
919   TOYOTA    CAMRY  4PTS 2.5L 4CIL 178HP AUT    2014    AUT  Gasolina
1027  TOYOTA    CAMRY  4PTS 2.5L 4CIL 175HP AUT    2011    AUT  Gasolina
1126  TOYOTA    CAMRY  4PTS 3.5L 6CIL 268HP AUT    2012    AUT  Gasolina
1127  TOYOTA    CAMRY  4PTS 3.5L 6CIL 268HP AUT    2013    AUT  Gasolina
1128  TOYOTA    CAMRY  4PTS 3.5L 6CIL 268HP AUT    2014    AUT  Gasolina
1480  TOYOTA    CAMRY  4PTS 3.5L 6CIL 268HP AUT    2011    AUT  Gasolina

      Cilindros  Potencia (HP)  Tamaño (L)      Categoría  R. Ciudad (km/l)  \
917           4            178         2.5  AUTOS DE LUJO             13.20
918           4            178         2.5  AUTOS DE LUJO             13.20
919           4            178         2.5  AUTOS DE LUJO             13.20
1027          4            175         2.5  AUTOS DE LUJO             12.15
1126          6            268         3.5  AUTOS DE LUJO             11.30
1127          6            268         3.5  AUTOS DE LUJO             11.30
1128          6            268         3.5  AUTOS DE LUJO             11.30
1480          6            268         3.5  AUTOS DE LUJO              9.40

      R. Carr. (km/l)  R. Comb. (km/l)  R. Ajust. (km/l)  CO2(g/km)  \
917              19.9            15.56             11.67        200
918              19.9            15.56             11.67        200
919              19.9            15.56             11.67        200
1027             19.0            14.50             10.88        214
1126             17.8            13.52             10.14        230
1127             17.8            13.52             10.14        230
1128             17.8            13.52             10.14        230
1480             13.2            10.80              8.10        288

      NOx (g/1000km)  Calificación Gas Ef. Inv. Calificación Contam. Aire
917               12                          7                         9
918               12                          7                         9
919               12                          7                         9
1027              56                          6                         5
1126              12                          6                         9
1127              12                          6                         9
1128              12                          6                         9
1480               6                          4                         9
501    TOYOTA
502    TOYOTA
503    TOYOTA
504    TOYOTA
505    TOYOTA
Name: Marca, dtype: object
0    8.8
1    9.4
dtype: float64

## Exploring Data With Pandas: Intermediate

- Using the **iloc method** to select using integer position. **the loc method is inclusive on the last item, while the iloc method is not**
- Use of isnull() to get a boolean series of data points where the values are empty and also the use of notnull()
- **Merging boolean** series with the & operator
- Mergin boolean series with the | operator
- Negating a series with the ~ operator
- Use of **sort_values()**
- Use of the **unique()** to get unique values

In [107]:
import numpy as np
test.loc[2:10, 'Trans.'] = np.nan
#test.loc[2:10]

null_values = test['Trans.'].isnull()
null_values.value_counts()
only_nulls_trans = test[null_values]

# Difference between integer positions and numeric indexing
print(only_nulls_trans.iloc[4])
print(only_nulls_trans.loc[4])

Marca                                                  HONDA
Submarca                                               CIVIC
Versión                      HÍBRIDO 4PTS 1.5L 4CIL 90HP CVT
Modelo                                                  2013
Trans.                                                   NaN
Comb.                                               Gasolina
Cilindros                                                  4
Potencia (HP)                                             90
Tamaño (L)                                               1.5
Categoría                                    AUTOS COMPACTOS
R. Ciudad (km/l)                                        23.8
R. Carr. (km/l)                                         26.7
R. Comb. (km/l)                                        26.15
R. Ajust. (km/l)                                       19.61
CO2(g/km)                                                119
NOx (g/1000km)                                             7
Calificación Gas Ef. Inv.                                 10
Calificación Contam. Aire                                  9
Name: 6, dtype: object
Marca                                                   FORD
Submarca                                              FUSION
Versión                      HYBRID 4PTS 2.5L 4CIL 156HP CVT
Modelo                                                  2011
Trans.                                                   NaN
Comb.                                               Gasolina
Cilindros                                                  4
Potencia (HP)                                            156
Tamaño (L)                                               2.5
Categoría                                    AUTOS COMPACTOS
R. Ciudad (km/l)                                          24
R. Carr. (km/l)                                         21.9
R. Comb. (km/l)                                        23.01
R. Ajust. (km/l)                                       17.26
CO2(g/km)                                                135
NOx (g/1000km)                                             5
Calificación Gas Ef. Inv.                                  9
Calificación Contam. Aire                                  9
Name: 4, dtype: object

In [116]:
#Combining boolean arrays with the & operator
only_compact_cars = test["Categoría"] == "AUTOS COMPACTOS"
only_toy_and_compact = only_toyotas_boolean & only_compact_cars
only_toy_and_compact.value_counts()

print(test[only_toy_and_compact])


#Making the same in a single statement

only_toy_and_compact_2 = (test["Marca"] == 'TOYOTA') & (test["Categoría"] == 'AUTOS COMPACTOS')
print((only_toy_and_compact == only_toy_and_compact_2).value_counts())

      Marca Submarca                       Versión  Modelo Trans.     Comb.  \
501  TOYOTA  COROLLA      4PTS 1.8L 4CIL 132HP MAN    2011    MAN  Gasolina
502  TOYOTA  COROLLA      4PTS 1.8L 4CIL 132HP AUT    2011    AUT  Gasolina
503  TOYOTA  COROLLA      4PTS 1.8L 4CIL 132HP MAN    2012    MAN  Gasolina
504  TOYOTA  COROLLA      4PTS 1.8L 4CIL 132HP AUT    2012    AUT  Gasolina
505  TOYOTA  COROLLA      4PTS 1.8L 4CIL 132HP AUT    2013    AUT  Gasolina
506  TOYOTA  COROLLA      4PTS 1.8L 4CIL 132HP MAN    2013    MAN  Gasolina
567  TOYOTA   MATRIX      5PTS 1.8L 4CIL 132HP MAN    2011    MAN  Gasolina
568  TOYOTA   MATRIX      5PTS 1.8L 4CIL 132HP AUT    2011    AUT  Gasolina
652  TOYOTA   AVANZA       5PTS 1.5L 4CIL 99HP MAN    2012    MAN  Gasolina
653  TOYOTA   AVANZA       5PTS 1.5L 4CIL 99HP AUT    2012    AUT  Gasolina
654  TOYOTA   AVANZA       5PTS 1.5L 4CIL 99HP AUT    2013    AUT  Gasolina
655  TOYOTA   AVANZA       5PTS 1.5L 4CIL 99HP MAN    2013    MAN  Gasolina
656  TOYOTA   AVANZA       5PTS 1.5L 4CIL 99HP MAN    2014    MAN  Gasolina
657  TOYOTA   AVANZA       5PTS 1.5L 4CIL 99HP AUT    2014    AUT  Gasolina
676  TOYOTA  COROLLA  XRS 4PTS 2.4L 4CIL 158HP MAN    2011    MAN  Gasolina
677  TOYOTA  COROLLA  XRS 4PTS 2.4L 4CIL 158HP AUT    2011    AUT  Gasolina
678  TOYOTA  COROLLA  XRS 4PTS 2.4L 4CIL 158HP MAN    2012    MAN  Gasolina
679  TOYOTA  COROLLA  XRS 4PTS 2.4L 4CIL 158HP AUT    2012    AUT  Gasolina
680  TOYOTA  COROLLA  XRS 4PTS 2.4L 4CIL 158HP AUT    2013    AUT  Gasolina
681  TOYOTA  COROLLA  XRS 4PTS 2.4L 4CIL 158HP MAN    2013    MAN  Gasolina
691  TOYOTA   AVANZA      5PTS 1.5L 4CIL 107HP MAN    2011    MAN  Gasolina
692  TOYOTA   AVANZA      5PTS 1.5L 4CIL 107HP AUT    2011    AUT  Gasolina
697  TOYOTA   MATRIX   XR 5PTS 2.4L 4CIL 158HP MAN    2011    MAN  Gasolina
698  TOYOTA   MATRIX   XR 5PTS 2.4L 4CIL 158HP AUT    2011    AUT  Gasolina

     Cilindros  Potencia (HP)  Tamaño (L)        Categoría  R. Ciudad (km/l)  \
501          4            132         1.8  AUTOS COMPACTOS             11.50
502          4            132         1.8  AUTOS COMPACTOS             11.50
503          4            132         1.8  AUTOS COMPACTOS             11.50
504          4            132         1.8  AUTOS COMPACTOS             11.50
505          4            132         1.8  AUTOS COMPACTOS             11.50
506          4            132         1.8  AUTOS COMPACTOS             11.50
567          4            132         1.8  AUTOS COMPACTOS             11.10
568          4            132         1.8  AUTOS COMPACTOS             11.10
652          4             99         1.5  AUTOS COMPACTOS              9.90
653          4             99         1.5  AUTOS COMPACTOS              9.90
654          4             99         1.5  AUTOS COMPACTOS              9.90
655          4             99         1.5  AUTOS COMPACTOS              9.90
656          4             99         1.5  AUTOS COMPACTOS              9.90
657          4             99         1.5  AUTOS COMPACTOS              9.90
676          4            158         2.4  AUTOS COMPACTOS              9.40
677          4            158         2.4  AUTOS COMPACTOS              9.40
678          4            158         2.4  AUTOS COMPACTOS              9.40
679          4            158         2.4  AUTOS COMPACTOS              9.40
680          4            158         2.4  AUTOS COMPACTOS              9.40
681          4            158         2.4  AUTOS COMPACTOS              9.40
691          4            107         1.5  AUTOS COMPACTOS              9.09
692          4            107         1.5  AUTOS COMPACTOS              9.09
697          4            158         2.4  AUTOS COMPACTOS              8.90
698          4            158         2.4  AUTOS COMPACTOS              8.90

     R. Carr. (km/l)  R. Comb. (km/l)  R. Ajust. (km/l)  CO2(g/km)  \
501            14.90            12.82              9.61        243
502            14.90            12.82              9.61        243
503            14.90            12.82              9.61        243
504            14.90            12.82              9.61        243
505            14.90            12.82              9.61        243
506            14.90            12.82              9.61        243
567            13.60            12.10              9.08        257
568            13.60            12.10              9.08        257
652            14.70            12.98              9.73        240
653            16.12            13.36             10.02        233
654            16.12            13.36             10.02        233
655            14.70            12.98              9.73        240
656            14.70            12.98              9.73        240
657            16.12            13.36             10.02        233
676            12.80            10.68              8.01        291
677            12.80            10.68              8.01        291
678            12.80            10.68              8.01        291
679            12.80            10.68              8.01        291
680            12.80            10.68              8.01        291
681            12.80            10.68              8.01        291
691            14.28            10.87              8.15        286
692            14.28            10.87              8.15        286
697            12.30            10.16              7.62        306
698            12.30            10.16              7.62        306

     NOx (g/1000km)  Calificación Gas Ef. Inv. Calificación Contam. Aire
501              16                          5                         8
502              16                          5                         8
503              16                          5                         8
504              16                          5                         8
505              16                          5                         8
506              16                          5                         8
567              16                          5                         8
568              16                          5                         8
652               6                          5                         9
653              10                          6                         9
654              10                          6                         9
655               6                          5                         9
656               6                          5                         9
657              10                          6                         9
676               7                          3                         9
677               7                          3                         9
678               7                          3                         9
679               7                          3                         9
680               7                          3                         9
681               7                          3                         9
691              10                          4                         9
692              10                          4                         9
697               7                          3                         9
698               7                          3                         9
True    4617
dtype: int64

In [118]:
#Sorting by name
sorted_by_brand = test.sort_values('Marca')
print(sorted_by_brand.head())
sorted_by_brand_desc = test.sort_values('Marca', ascending=False)
print(sorted_by_brand_desc.head())

      Marca Submarca                           Versión  Modelo Trans.  \
4376  ACURA      RDX      2WD 5PTS 3.5L 6CIL 279HP AUT    2016    AUT
952   ACURA      ILX     TECH 4PTS 2.0L 4CIL 150HP AUT    2013    AUT
951   ACURA      ILX  PREMIUM 4PTS 2.0L 4CIL 150HP AUT    2013    AUT
948   ACURA      ILX     BASE 4PTS 2.0L 4CIL 150HP AUT    2015    AUT
947   ACURA      ILX  PREMIUM 4PTS 2.0L 4CIL 150HP AUT    2015    AUT

         Comb.  Cilindros  Potencia (HP)  Tamaño (L)  \
4376  Gasolina          6            279         3.5
952   Gasolina          4            150         2.0
951   Gasolina          4            150         2.0
948   Gasolina          4            150         2.0
947   Gasolina          4            150         2.0

                             Categoría  R. Ciudad (km/l)  R. Carr. (km/l)  \
4376  CAMIONETAS DE USO MULTIPLE (SUV)              6.80            14.00
952                      AUTOS DE LUJO             12.76            20.57
951                      AUTOS DE LUJO             12.76            20.57
948                      AUTOS DE LUJO             12.80            20.60
947                      AUTOS DE LUJO             12.80            20.60

      R. Comb. (km/l)  R. Ajust. (km/l)  CO2(g/km)  NOx (g/1000km)  \
4376            10.15              7.61        306               4
952             15.39             11.54        202              10
951             15.39             11.54        202              10
948             16.82             12.61        185               8
947             16.82             12.61        185               8

      Calificación Gas Ef. Inv. Calificación Contam. Aire
4376                          3                         9
952                           7                         9
951                           7                         9
948                           7                         9
947                           7                         9
     Marca Submarca                               Versión  Modelo Trans.  \
639     VW     GOLF  SPORTWAGEN 5PTS 2.5L 5CIL 0170HP DSG    2012    AUT
532     VW   BEETLE             2PTAS 2.5L 5CIL 170HP MAN    2016    MAN
514     VW    JETTA         MKVI 4PTS 2.5L 5CIL 170HP MAN    2013    MAN
4112    VW  TOUAREG     5PTAS 3.6L 6CIL 280HP TIP 4MOTION    2016   TIPT
4113    VW  TOUAREG     5PTAS 3.6L 6CIL 280HP TIP 4MOTION    2017   TIPT

         Comb.  Cilindros  Potencia (HP)  Tamaño (L)  \
639   Gasolina          5            170         2.5
532   Gasolina          5            170         2.5
514   Gasolina          5            170         2.5
4112  Gasolina          6            280         3.6
4113  Gasolina          6            280         3.6

                             Categoría  R. Ciudad (km/l)  R. Carr. (km/l)  \
639                    AUTOS COMPACTOS             10.11            17.01
532                    AUTOS COMPACTOS             11.30            19.40
514                    AUTOS COMPACTOS             11.48            20.66
4112  CAMIONETAS DE USO MULTIPLE (SUV)              8.20            13.00
4113  CAMIONETAS DE USO MULTIPLE (SUV)              8.20            13.00

      R. Comb. (km/l)  R. Ajust. (km/l)  CO2(g/km)  NOx (g/1000km)  \
639             12.37              9.28        251              37
532             13.91             10.44        223              14
514             14.35             10.76        217              28
4112             9.83              7.38        316              33
4113             9.83              7.38        316              33

      Calificación Gas Ef. Inv. Calificación Contam. Aire
639                           5                         6
532                           6                         8
514                           6                         6
4112                          3                         6
4113                          3                         6

In [120]:
brands_in_dataset= test["Marca"].unique()
print(brands_in_dataset)
print(type(brands_in_dataset))

['FORD' 'HONDA' 'SEAT' 'MAZDA' 'CHEVROLET' 'VW' 'SUZUKI' 'NISSAN'
 'HYUNDAI' 'FIAT' 'MITSUBISHI' 'KIA' 'MERCEDES' 'DODGE' 'RENAULT'
 'PEUGEOT' 'TOYOTA' 'BMW' 'AUDI' 'MINI' 'SUBARU' 'INFINITI' 'VOLVO'
 'ALFA ROMEO' 'PORSCHE' 'ACURA' 'CADILLAC' 'CHRYSLER' 'LINCOLN' 'BUICK'
 'SAAB' 'LEXUS' 'JAGUAR' 'BENTLEY' 'ROLLSROYCE' 'MAYBACH' 'LAMBORGHINI'
 'SMART' 'LAND ROVER' 'GML' 'JEEP' 'MERCURY' 'GMC']
<class 'numpy.ndarray'>

## Data Cleaning Basics

- Solving encodings with the data
- Get the column labels of the data and overwrite the column labels
- Use the vectorized string methods to clean data.
- Change the types of a series with the astype() method
- Use of the dropna() function to delete either all rows (0) or columns(0) that contains at least one data point with NA
- Save a data frame with **df.to_csv()**

In [124]:
test.columns

Index(['Marca', 'Submarca', 'Versión', 'Modelo', 'Trans.', 'Comb.',
       'Cilindros', 'Potencia (HP)', 'Tamaño (L)', 'Categoría',
       'R. Ciudad (km/l)', 'R. Carr. (km/l)', 'R. Comb. (km/l)',
       'R. Ajust. (km/l)', 'CO2(g/km)', 'NOx (g/1000km)',
       'Calificación Gas Ef. Inv.', 'Calificación Contam. Aire'],
      dtype='object')

In [127]:
#Use of vectorized string operations
brands = test["Marca"]
print(brands.head())
print(brands.str.lower().head())

0    FORD
1    FORD
2    FORD
3    FORD
4    FORD
Name: Marca, dtype: object
0    ford
1    ford
2    ford
3    ford
4    ford
Name: Marca, dtype: object

In [131]:
#Changing the type of a series
print(test.info())
test["Modelo"] = test["Modelo"].astype(str)
print(test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4617 entries, 0 to 4616
Data columns (total 18 columns):
Marca                        4617 non-null object
Submarca                     4617 non-null object
Versión                      4617 non-null object
Modelo                       4617 non-null int64
Trans.                       4592 non-null object
Comb.                        4617 non-null object
Cilindros                    4617 non-null int64
Potencia (HP)                4617 non-null int64
Tamaño (L)                   4617 non-null float64
Categoría                    4617 non-null object
R. Ciudad (km/l)             4617 non-null float64
R. Carr. (km/l)              4617 non-null float64
R. Comb. (km/l)              4617 non-null float64
R. Ajust. (km/l)             4617 non-null float64
CO2(g/km)                    4617 non-null int64
NOx (g/1000km)               4617 non-null int64
Calificación Gas Ef. Inv.    4617 non-null int64
Calificación Contam. Aire    4617 non-null object
dtypes: float64(5), int64(6), object(7)
memory usage: 649.3+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4617 entries, 0 to 4616
Data columns (total 18 columns):
Marca                        4617 non-null object
Submarca                     4617 non-null object
Versión                      4617 non-null object
Modelo                       4617 non-null object
Trans.                       4592 non-null object
Comb.                        4617 non-null object
Cilindros                    4617 non-null int64
Potencia (HP)                4617 non-null int64
Tamaño (L)                   4617 non-null float64
Categoría                    4617 non-null object
R. Ciudad (km/l)             4617 non-null float64
R. Carr. (km/l)              4617 non-null float64
R. Comb. (km/l)              4617 non-null float64
R. Ajust. (km/l)             4617 non-null float64
CO2(g/km)                    4617 non-null int64
NOx (g/1000km)               4617 non-null int64
Calificación Gas Ef. Inv.    4617 non-null int64
Calificación Contam. Aire    4617 non-null object
dtypes: float64(5), int64(5), object(8)
memory usage: 649.3+ KB
None

In [132]:
#Change a label
test.rename({"Modelo": "MODELO"}, axis = 1, inplace=True)
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4617 entries, 0 to 4616
Data columns (total 18 columns):
Marca                        4617 non-null object
Submarca                     4617 non-null object
Versión                      4617 non-null object
MODELO                       4617 non-null object
Trans.                       4592 non-null object
Comb.                        4617 non-null object
Cilindros                    4617 non-null int64
Potencia (HP)                4617 non-null int64
Tamaño (L)                   4617 non-null float64
Categoría                    4617 non-null object
R. Ciudad (km/l)             4617 non-null float64
R. Carr. (km/l)              4617 non-null float64
R. Comb. (km/l)              4617 non-null float64
R. Ajust. (km/l)             4617 non-null float64
CO2(g/km)                    4617 non-null int64
NOx (g/1000km)               4617 non-null int64
Calificación Gas Ef. Inv.    4617 non-null int64
Calificación Contam. Aire    4617 non-null object
dtypes: float64(5), int64(5), object(8)
memory usage: 649.3+ KB

In [134]:
#Use the map method to replace several values on a series with one command
replacing = {
    'FORD': 'CHaja'
}

brands = brands.map(replacing)
print(brands)

0       CHaja
1       CHaja
2       CHaja
3       CHaja
4       CHaja
5       CHaja
6         NaN
7         NaN
8         NaN
9         NaN
10        NaN
11        NaN
12        NaN
13        NaN
14        NaN
15        NaN
16        NaN
17        NaN
18        NaN
19        NaN
20        NaN
21        NaN
22        NaN
23        NaN
24        NaN
25        NaN
26        NaN
27        NaN
28        NaN
29        NaN
        ...
4587      NaN
4588      NaN
4589      NaN
4590      NaN
4591      NaN
4592      NaN
4593      NaN
4594      NaN
4595      NaN
4596      NaN
4597      NaN
4598      NaN
4599      NaN
4600      NaN
4601      NaN
4602      NaN
4603      NaN
4604      NaN
4605      NaN
4606      NaN
4607      NaN
4608      NaN
4609      NaN
4610      NaN
4611      NaN
4612      NaN
4613      NaN
4614      NaN
4615      NaN
4616      NaN
Name: Marca, Length: 4617, dtype: object

In [141]:
#Usefull command to get how many null values are per column
print(test.isnull().sum())

Marca                         0
Submarca                      0
Versión                       0
MODELO                        0
Trans.                       25
Comb.                         0
Cilindros                     0
Potencia (HP)                 0
Tamaño (L)                    0
Categoría                     0
R. Ciudad (km/l)              0
R. Carr. (km/l)               0
R. Comb. (km/l)               0
R. Ajust. (km/l)              0
CO2(g/km)                     0
NOx (g/1000km)                0
Calificación Gas Ef. Inv.     0
Calificación Contam. Aire     0
dtype: int64

In [142]:
print(test.dropna(1).info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4617 entries, 0 to 4616
Data columns (total 17 columns):
Marca                        4617 non-null object
Submarca                     4617 non-null object
Versión                      4617 non-null object
MODELO                       4617 non-null object
Comb.                        4617 non-null object
Cilindros                    4617 non-null int64
Potencia (HP)                4617 non-null int64
Tamaño (L)                   4617 non-null float64
Categoría                    4617 non-null object
R. Ciudad (km/l)             4617 non-null float64
R. Carr. (km/l)              4617 non-null float64
R. Comb. (km/l)              4617 non-null float64
R. Ajust. (km/l)             4617 non-null float64
CO2(g/km)                    4617 non-null int64
NOx (g/1000km)               4617 non-null int64
Calificación Gas Ef. Inv.    4617 non-null int64
Calificación Contam. Aire    4617 non-null object
dtypes: float64(5), int64(5), object(7)
memory usage: 613.3+ KB
None

## Guided Project

- Displaying top and last columns only with the data set
- Using df.drop() to drop certain columns (axis = 1)
- Use of **sort_index()** to sort by the index
- Get only a certain number of chars from a series
- Use the **normalize = True** parameter to get value_counts as a percentage

In [143]:
test

,Marca,Submarca,Versión,MODELO,Trans.,Comb.,Cilindros,Potencia (HP),Tamaño (L),Categoría,R. Ciudad (km/l),R. Carr. (km/l),R. Comb. (km/l),R. Ajust. (km/l),CO2(g/km),NOx (g/1000km),Calificación Gas Ef. Inv.,Calificación Contam. Aire
0,FORD,FUSION,HIBRIDO 4PTS 2.0L 4CIL 188HP AUT (CVT),2015,CVT,Gasolina,4,188,2.000,AUTOS COMPACTOS,27.44,28.57,28.93,21.70,107,5,10,9
1,FORD,FUSION,HIBRIDO 4PTS 2.0L 4CIL 188HP AUT (eCVT),2016,CVT,Gasolina,4,188,2.000,AUTOS COMPACTOS,27.44,28.57,28.93,21.70,107,0,10,9
2,FORD,FUSION,HIBRIDO 4X2 4PTAS 2.0L 4CIL 141(+47e)HP E-CVT,2017,NaN,Gasolina,4,188,2.000,AUTOS COMPACTOS,25.62,24.77,25.23,18.92,123,2,10,9
3,FORD,FUSION,HIBRIDO 4PTAS 2.0L 4CIL 188HP AUT eCVT,2018,NaN,Gasolina,4,188,2.000,AUTOS COMPACTOS,25.62,24.77,25.23,18.92,123,2,10,9
4,FORD,FUSION,HYBRID 4PTS 2.5L 4CIL 156HP CVT,2011,NaN,Gasolina,4,156,2.500,AUTOS COMPACTOS,24.00,21.90,23.01,17.26,135,5,9,9
5,FORD,FUSION,HYBRID 4PTS 2.5L 4CIL 156HP CVT,2012,NaN,Gasolina,4,156,2.500,AUTOS COMPACTOS,24.00,21.90,23.01,17.26,135,6,9,9
6,HONDA,CIVIC,HÍBRIDO 4PTS 1.5L 4CIL 90HP CVT,2013,NaN,Gasolina,4,90,1.500,AUTOS COMPACTOS,23.80,26.70,26.15,19.61,119,7,10,9
7,HONDA,CIVIC,HÍBRIDO 4PTS 1.5L 4CIL 90HP CVT,2014,NaN,Gasolina,4,90,1.500,AUTOS COMPACTOS,23.80,26.70,26.15,19.61,119,7,10,9
8,HONDA,CIVIC,HÍBRIDO 4PTS 1.5L 4CIL 90HP CVT,2012,NaN,Gasolina,4,90,1.500,AUTOS COMPACTOS,23.20,26.10,24.42,18.32,127,7,9,9
9,HONDA,CIVIC HIBRIDO,4PTS 1.3L 4CIL 110HP CVT,2011,NaN,Gasolina,4,110,1.300,AUTOS COMPACTOS,21.80,25.40,23.29,17.46,134,10,9,9
10,SEAT,TOLEDO,SEDAN 4PUERTAS 1.2L 4CIL 105HP MAN TURBO,2015,NaN,Gasolina,4,105,1.200,AUTOS COMPACTOS,17.50,22.80,19.54,14.66,159,15,8,8
11,SEAT,TOLEDO,4PTAS 1.4L 4CIL125HP DSG TURBO,2016,DSG,Gasolina,4,125,1.400,AUTOS COMPACTOS,17.30,27.00,20.64,15.48,151,25,9,6
12,SEAT,TOLEDO,4PTAS 1.4L 4CIL125HP DSG TURBO,2017,DSG,Gasolina,4,125,1.400,AUTOS COMPACTOS,17.30,27.00,20.64,15.48,151,25,9,6
13,MAZDA,MAZDA2,HATCHBACK 5PTAS 1.5L 4CIL 102HP AUT,2016,AUT,Gasolina,4,102,1.500,AUTOS COMPACTOS,17.30,24.00,19.79,14.84,157,9,8,9
14,MAZDA,MAZDA2,i TOURING 5PTAS 1.5L 4CIL 106HP AUT R15,2016,AUT,Gasolina,4,106,1.500,AUTOS COMPACTOS,17.30,24.00,21.10,15.83,147,9,9,9
15,MAZDA,MAZDA2,i GRAND TOURING 5PTAS 1.5L 4CIL 106HP AUT R16,2016,AUT,Gasolina,4,106,1.500,AUTOS COMPACTOS,17.30,24.00,21.10,15.83,147,9,9,9
16,MAZDA,MAZDA2,i 5PTAS 1.5L 4CIL 106HP AUT,2017,AUT,Gasolina,4,106,1.496,AUTOS COMPACTOS,17.30,24.00,21.10,15.83,147,9,9,9
17,MAZDA,MAZDA2,i TOURING 5PTAS 1.5L 4CIL 106HP AUT,2017,AUT,Gasolina,4,106,1.496,AUTOS COMPACTOS,17.30,24.00,21.10,15.83,147,9,9,9
18,MAZDA,MAZDA2,i GRAND TOURING 5PTAS 1.5L 4CIL 106HP AUT,2017,AUT,Gasolina,4,106,1.496,AUTOS COMPACTOS,17.30,24.00,21.10,15.83,147,9,9,9
19,CHEVROLET,CRUZE,LS 4PTAS 1.4L 4CIL 148HP AUT TURBO,2017,AUT,Gasolina,4,148,1.400,AUTOS COMPACTOS,17.14,28.41,22.15,16.61,140,13,9,?
20,CHEVROLET,CRUZE,LT 4PTAS 1.4L 4CIL 148HP AUT TURBO,2017,AUT,Gasolina,4,148,1.400,AUTOS COMPACTOS,17.14,28.41,22.15,16.61,140,13,9,?
21,VW,GOLF,A7 5PTS 1.4L 4CIL 140HP DSG TURBO FSI,2015,DSG,Gasolina,4,140,1.400,AUTOS COMPACTOS,17.10,27.90,20.71,15.53,150,41,9,6
22,VW,JETTA,MKVI 4PTS 2.0L 4CIL 140HP DSG TURBO DIESEL,2015,DSG,Diesel,4,140,2.000,AUTOS COMPACTOS,17.00,26.10,21.47,16.10,166,95,8,?
23,VW,JETTA,MKVI 4PTAS 2.0L 4CIL 140HP DSG TURBO DIESEL,2016,DSG,Diesel,4,140,2.000,AUTOS COMPACTOS,17.00,26.10,21.47,16.10,166,95,8,?
24,CHEVROLET,CRUZE,LS 4PTAS 1.4L 4CIL 148HP MAN TURBO,2017,MAN,Gasolina,4,148,1.400,AUTOS COMPACTOS,16.99,27.12,21.72,16.29,143,31,9,?
25,SEAT,TOLEDO,4PTAS 1.2L 4CIL110HP MAN,2016,MAN,Gasolina,4,110,1.200,AUTOS COMPACTOS,16.90,26.70,20.24,15.18,154,19,8,7
26,SEAT,TOLEDO,4PTAS 1.2L 4CIL110HP MAN,2017,MAN,Gasolina,4,110,1.200,AUTOS COMPACTOS,16.90,26.70,20.24,15.18,154,19,8,7
27,CHEVROLET,CAVALIER,LT 4PTAS 1.5L 4CIL 107HP AUT,2018,AUT,Gasolina,4,107,1.500,AUTOS COMPACTOS,16.59,24.15,20.64,15.48,151,36,9,?
28,CHEVROLET,CAVALIER,PREMIER 4PTAS 1.5L 4CIL 107HP AUT,2018,AUT,Gasolina,4,107,1.500,AUTOS COMPACTOS,16.59,24.15,20.64,15.48,151,36,9,?
29,SUZUKI,S-CROSS,2WD 5PTAS 1.6L 4CIL118HP CVT,2016,CVT,Gasolina,4,118,1.600,AUTOS COMPACTOS,16.50,21.70,18.49,13.87,168,7,8,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4587,LAND ROVER,RANGE ROVER,4X4 5PTS 5.0L 8CIL 506HP AUT SUPERCARGADA,2014,AUT,Gasolina,8,506,5.000,CAMIONETAS DE USO MULTIPLE (SUV),5.09,8.40,7.34,5.51,423,10,0,9
4588,LAND ROVER,RANGE ROVER,SPORT HSE 4PTS 5.0L 8CIL 375HP AUT,2011,AUT,Gasolina,8,375,5.000,CAMIONETAS DE USO MULTIPLE (SUV),5.05,9.52,7.57,5.68,411,24,0,?
4589,LAND ROVER,RANGE ROVER,SPORT HSE 5PTS 5.0L 8CIL 375HP AUT,2012,AUT,Gasolina,8,375,5.000,CAMIONETAS DE USO MULTIPLE (SUV),5.05,9.53,7.57,5.68,410,24,0,?
4590,LAND ROVER,RANGE ROVER,SPORT HSE 5PTS 5.0L 8CIL 375HP AUT,2013,AUT,Gasolina,8,375,5.000,CAMIONETAS DE USO MULTIPLE (SUV),5.05,9.52,7.57,5.68,411,24,0,?
4591,MERCEDES,G500,5PTS 5.5L 8CIL 382HP AUT,2012,AUT,Gasolina,8,382,5.461,CAMIONETAS DE USO MULTIPLE (SUV),5.00,8.40,7.26,5.45,428,56,0,?
4592,MERCEDES,G500,CONVERTIBLE 2PTS 5.5L 8CIL 382HP AUT,2012,AUT,Gasolina,8,382,5.500,CAMIONETAS DE USO MULTIPLE (SUV),5.00,8.40,7.26,5.45,428,56,0,?
4593,MERCEDES,G500,5PTS 5.5L 8CIL 382HP AUT,2013,AUT,Gasolina,8,382,5.461,CAMIONETAS DE USO MULTIPLE (SUV),5.00,8.40,7.26,5.45,428,56,0,?
4594,MERCEDES,G500,CONVERTIBLE 2PTS 5.5L 8CIL 382HP AUT,2013,AUT,Gasolina,8,382,5.500,CAMIONETAS DE USO MULTIPLE (SUV),5.00,8.40,7.26,5.45,428,56,0,?
4595,MERCEDES,G500,CONVERTIBLE 2PTS 5.5L 8CIL 382HP AUT,2014,AUT,Gasolina,8,382,5.500,CAMIONETAS DE USO MULTIPLE (SUV),5.00,8.40,7.26,5.45,428,56,0,?
4596,MERCEDES,G500,L 5PTS 5.5L 8CIL 382HP AUT,2014,AUT,Gasolina,8,382,5.461,CAMIONETAS DE USO MULTIPLE (SUV),5.00,8.40,7.26,5.45,428,53,0,?
4597,PORSCHE,CAYENNE,GTS 4X4 5PTS 4.8L 8CIL 405HP TIP QUATTRO,2012,TIP,Gasolina,8,405,4.800,CAMIONETAS DE USO MULTIPLE (SUV),4.85,9.80,6.28,4.71,495,19,0,7
4598,PORSCHE,CAYENNE,S 4X4 5PTS 4.8L 8CIL 400HP TIP QUATTRO,2012,TIP,Gasolina,8,400,4.800,CAMIONETAS DE USO MULTIPLE (SUV),4.85,9.80,6.28,4.71,495,19,0,7
4599,PORSCHE,CAYENNE,S 6PTS 4.8L 8CIL 400HP TIP,2011,TIP,Gasolina,8,400,4.800,CAMIONETAS DE USO MULTIPLE (SUV),4.85,9.80,6.28,4.71,495,19,0,7
4600,PORSCHE,CAYENNE,GTS 5PTS 4.8L 8CIL 405HP TIP,2011,TIP,Gasolina,8,405,4.800,CAMIONETAS DE USO MULTIPLE (SUV),4.85,9.80,6.28,4.71,495,19,0,7
4601,LAND ROVER,RANGE ROVER,SUPERCARGADA 4WD 5PTS 5.0L 8CIL 506HP AUT,2013,AUT,Gasolina,8,506,5.000,CAMIONETAS DE USO MULTIPLE (SUV),4.85,10.10,7.49,5.62,415,16,0,?
4602,LAND ROVER,RANGE ROVER,HSE 4PTS 5.0L 8CIL 375HP AUT,2011,AUT,Gasolina,8,375,5.000,CAMIONETAS DE USO MULTIPLE (SUV),4.80,10.00,7.43,5.57,419,14,0,?
4603,LAND ROVER,RANGE ROVER,HSE 5PTS 5.0L 8CIL 375HP AUT,2012,AUT,Gasolina,8,375,5.000,CAMIONETAS DE USO MULTIPLE (SUV),4.80,10.00,7.43,5.57,419,14,0,?
4604,LAND ROVER,RANGE ROVER,HSE 5PTS 5.0L 8CIL 375HP AUT,2013,AUT,Gasolina,8,375,5.000,CAMIONETAS DE USO MULTIPLE (SUV),4.80,10.00,7.43,5.57,419,14,0,?
4605,MERCEDES,G55 AMG,5PTS 5.5L 8CIL 493HP AUT,2011,AUT,Gasolina,8,493,5.500,CAMIONETAS DE USO MULTIPLE (SUV),4.67,7.87,6.83,5.13,455,14,0,?
4606,MERCEDES,G55,AMG 5PTS 5.4L 8CIL 500HP AUT TURBO,2012,AUT,Gasolina,8,500,5.400,CAMIONETAS DE USO MULTIPLE (SUV),4.63,7.94,6.82,5.11,456,32,0,?
4607,PORSCHE,CAYENNE,S 4X4 5PTS 4.8L 8CIL 500HP TIP QUATTRO BITURBO,2012,TIP,Gasolina,8,500,4.800,CAMIONETAS DE USO MULTIPLE (SUV),4.44,9.52,5.85,4.39,532,24,0,7
4608,PORSCHE,CAYENNE,S 4X4 5PTS 4.8L 8CIL 550HP TIP QUATTRO BITURBO,2012,TIP,Gasolina,8,550,4.800,CAMIONETAS DE USO MULTIPLE (SUV),4.44,9.52,5.85,4.39,532,24,0,7
4609,PORSCHE,CAYENNE,TURBO S 5PTS 4.8L 8CIL 500HP TIP,2011,TIP,Gasolina,8,500,4.800,CAMIONETAS DE USO MULTIPLE (SUV),4.44,9.52,5.84,4.38,532,24,0,7
4610,PORSCHE,CAYENNE,TURBO S 5PTS 4.8L 8CIL 550HP TIP,2011,TIP,Gasolina,8,500,4.800,CAMIONETAS DE USO MULTIPLE (SUV),4.44,9.52,5.84,4.38,532,24,0,7
4611,LAND ROVER,RANGE ROVER,SUPERCARGADA 4PTS 5.0L 8CIL 506HP AUT,2011,AUT,Gasolina,8,506,5.000,CAMIONETAS DE USO MULTIPLE (SUV),4.42,9.60,6.97,5.22,446,39,0,?
4612,LAND ROVER,RANGE ROVER,SUPERCARGADA 5PTS 5.0L 506HP AUT,2012,AUT,Gasolina,8,506,5.000,CAMIONETAS DE USO MULTIPLE (SUV),4.42,9.60,6.97,5.22,446,39,0,?
4613,LAND ROVER,RANGE ROVER,SUPERCARGADA 5PTS 5.0L 8CIL 506HP AUT,2013,AUT,Gasolina,8,506,5.000,CAMIONETAS DE USO MULTIPLE (SUV),4.42,9.60,6.97,5.22,446,39,0,?
4614,MERCEDES,G 65,AMG 4X4 5PTAS 6.0L 12CIL 630HP AUT BITURBO,2016,AUT,Gasolina,12,630,5.980,CAMIONETAS DE USO MULTIPLE (SUV),4.41,7.30,6.45,4.84,482,38,0,?
4615,MERCEDES,G 65,AMG 5PTAS 6.0L 12CIL 630HP BITURBO AUT,2018,AUT,Gasolina,12,630,5.980,CAMIONETAS DE USO MULTIPLE (SUV),4.41,7.30,6.45,4.84,482,38,0,?
4616,MERCEDES,ML63 AMG,5PTS 6.2L 8CIL 503HP AUT,2011,G TRONIC,Gasolina,8,503,6.200,CAMIONETAS DE USO MULTIPLE (SUV),4.14,8.19,5.33,3.99,584,31,0,6

In [145]:
test["MODELO"].value_counts().sort_index()

2011    628
2012    689
2013    680
2014    510
2015    430
2016    872
2017    599
2018    209
Name: MODELO, dtype: int64

In [160]:
test["MODELO"] = test["MODELO"].astype(int)
between_2014_2016 = (test["MODELO"] >= 2014) & (test["MODELO"] <= 2016)
test[between_2014_2016]["MODELO"].value_counts().sort_index()

2014    510
2015    430
2016    872
Name: MODELO, dtype: int64

In [163]:
test["Marca"].head().index.tolist()

[0, 1, 2, 3, 4]

In [167]:
test["Marca"].value_counts(normalize = True)

AUDI           0.091835
PORSCHE        0.090968
MERCEDES       0.081005
VW             0.069092
CHEVROLET      0.064111
BMW            0.057830
FORD           0.055664
NISSAN         0.044185
HONDA          0.043968
MAZDA          0.034655
DODGE          0.028373
MINI           0.027507
SEAT           0.022742
TOYOTA         0.019926
PEUGEOT        0.019710
JEEP           0.017977
VOLVO          0.017544
SUBARU         0.016677
CADILLAC       0.016677
SUZUKI         0.016244
FIAT           0.015378
ACURA          0.014512
HYUNDAI        0.011912
INFINITI       0.011912
MITSUBISHI     0.011263
LINCOLN        0.011046
BENTLEY        0.010830
RENAULT        0.010180
KIA            0.009747
LAND ROVER     0.008664
JAGUAR         0.007147
CHRYSLER       0.006931
SMART          0.006714
BUICK          0.006498
GMC            0.006281
LAMBORGHINI    0.003682
ALFA ROMEO     0.003682
ROLLSROYCE     0.003249
SAAB           0.001733
GML            0.000866
MERCURY        0.000433
LEXUS          0.000433
MAYBACH        0.000217
Name: Marca, dtype: float64

In [169]:
# build a custom series with a dictionary
my_dicti = {"contador": 100, "financiero": 150, "quant": 1000}
my_series = pd.Series(my_dicti)
my_series

contador       100
financiero     150
quant         1000
dtype: int64

In [174]:
#creating a data frame
cost_of_living = [15000, 30940, 209384]
my_dataframe = pd.DataFrame(my_series, columns = ['salary'])
my_dataframe

            salary
contador       100
financiero     150
quant         1000